function rna_to_aa(rna::String)
	encoding = Dict(
			"UUU" => "F", "CUU" => "L", "AUU" => "I", "GUU" => "V",
			"UUC" => "F", "CUC" => "L", "AUC" => "I", "GUC" => "V",
			"UUA" => "L", "CUA" => "L", "AUA" => "I", "GUA" => "V",
			"UUG" => "L", "CUG" => "L", "AUG" => "M", "GUG" => "V",
			"UCU" => "S", "CCU" => "P", "ACU" => "T", "GCU" => "A",
			"UCC" => "S", "CCC" => "P", "ACC" => "T", "GCC" => "A",
			"UCA" => "S", "CCA" => "P", "ACA" => "T", "GCA" => "A",
			"UCG" => "S", "CCG" => "P", "ACG" => "T", "GCG" => "A",
			"UAU" => "Y", "CAU" => "H", "AAU" => "N", "GAU" => "D",
			"UAC" => "Y", "CAC" => "H", "AAC" => "N", "GAC" => "D",
			"UAA" => 0,   "CAA" => "Q", "AAA" => "K", "GAA" => "E",
			"UAG" => 0,   "CAG" => "Q", "AAG" => "K", "GAG" => "E",
			"UGU" => "C", "CGU" => "R", "AGU" => "S", "GGU" => "G",
			"UGC" => "C", "CGC" => "R", "AGC" => "S", "GGC" => "G",
			"UGA" => 0,   "CGA" => "R", "AGA" => "R", "GGA" => "G",
			"UGG" => "W", "CGG" => "R", "AGG" => "R", "GGG" => "G"
		)
	translation = ""
	for i in 1:3:length(rna)
		aa = encoding[rna[i:i+2]]
		if aa == 0
			return translation
		else
			translation *= aa
		end
	end
	return translation
end


@testset "Sample & Test Datasets" begin
	sample_dataset = "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"
	sample_output  = "MAMAPRTEINSTRING"
	
	file = open("datasets/rosalind_prot.txt", "r")
	test_dataset = read(file, String)
	close(file)
	test_output = "MSGSEREADPSVVLIIHPSTPPSLACTRLSGQMLNLVLHLINCSSANHAALLDTEIIFYITWADVQSPLTARYVRKLRPSASATSYQLGNGRLRTNNMPTPLAEAASYGIAVRLRRDQITAQPTAHLFTPLVSAICYMNFSISSPLPPGGSISPLVIQFAVRGSLGGLRGWLWSSRCQNNEMHTAHEPDQVNVPQFGLLIDANIIRPIELLVAPRSSCSPHGMLGGACQISRVSLCAASVPVRVGRLSLRLDEHATYLAAPESSFSSSCARACLVGIQPLESRIPLCRLTPCPVVLTCTDERVSLFHIFTKLMTGREFVLVGDSAVPRCRDIIILGPFRTPHQNLAPQLRGYYTSKRVGQTESPTYSAVVVTGTPNVRSYVGPFHDCLKPVGLKYDDCSGAWAPLTLGHGIGIAILPKQRLPALNFFWKGKSSNLYINGIRGVPPSVPLALIHSRRISMSPLRGHQLIKVYAIMAVQRWLYIYANQFTVREAALKSHTVEEQSITRFIIRCLEVVGYYRSRSSGKHVYCTGRLIILSMWTPVSDRRPKAWARVADAGNHTYLQYLLLINYPLSDFRVWAPQERRGRSANQYVGAFLKNTGGGNVPLDRYKFGQHHLTDVPNTPVYPTRMDASKAGTRCPPIRCRLRPVYASRIIVDSGPQRACIHTEALPIVQEVDASGEITTATPGFPRKRIVVKYARSRHAPRTFKVFSLYPPVFVYTQVLSSVDMCGIQLADGLLHLPTTTDSSSFFRVSRAAIIDWAKRCQEAFPALTRSTSTILGGCSYPVARPTRLIQDTQLKVWWSAYERGWLRVPYYKGIEYGKAPESPCAVADLAGQSNSCCFVQSDTPNDGTATASTLESPLNRLRFAIPHMGSTTGCLGKDCDIRGETVKRSTRNAQVGGIETFPGFGPGFYLTVVYVNEGLVMGPYQICHFTPVNTVHEASAKSLYVQHQCPLIQANARLEHLLKPPHAVASGGDSVKIQSCKILVCIRQIESGEKDVQNLSPRTLLTRPLSTYGGSFSANTWRKFPNWTCVVDDYRSVVADRNSRQPSNLRWASTPLLHRGIVRSSCATLLTSVHDDDRCTQEAHSGSSGYLVGTEAANTHNLGYFTDQCSMSGIRKPRKATVYPWAQHSSHERHMCCSATSSYARVSIMERTPQPAKWKVTPKTQSTRPRAAPTQFSELSPFFVPADLSRTLRCTGLTTSTRLVPALALDTRRALGTLSGPWGDSHSPVSVEKVAVFRWGLSKSAWETCGPAQQVTELLFNYLYRCALHRKELRKGAGTRHCSVLAISCGLGNVHSRVQHLILSDDCAIRRIGCAGARRTKAIPCRIDSLRLLSVRRDNFPESVPCTVTQRACIFCELFTKRLSRGKTVACVEELDEKEYVRPRHYCMLFWIGSLNLVPMPPRDAVSGRRCSHRWYSGASIVTEGLHLCCTQPPFKFAKSFLADSGYRWNRPVYKKPLLPPVHQCEAIPSKCTGATSTISHLRKTPRSSTVNTPLLPVRPTYYTSPLLSLGGSATDPVGVGIPVAIKILSHATRAYAIPFTCKHSIKGRPNASQEIIESRRASPRSEVMSVKRQNLYLGRSSLGAMSLIRDSWAAHIYSIPSQDVLASRRTLRHRSVLESDATGYSLGTSLGMRLADPCCKYPLALVETTDSQHASRKGRRRASEVAHGGGRDGHCLSIGGDARSKVGPIGSVALWIVILVCWACNVEIMNWECLPESRSAITRRLYHASGKLHACLRSSMLRSSVNTWYDLAEFIYIRWAVSQPQPTRQGHCAEFQLIVQEDVPSPFTQSTSESSILVLTLIKSTQGLSLYLVLLALVELYANINSLANTALCLCNGWVRTGGRDESHPCNAYAAARRESFGISLQIQLFLVLFLAPYRGEGARPYRLLNTVSQSRGRELHTRPIWFSVSYTCLRVGKRVLPERVTNILRIMQLTDLGLYYGGCCYTGSHASQKGTEGQPFRRLDSLSSIYSRPWSLTRGLFCLFTHATFACVDVQCEARKQLRGTTHQHRPTDARVQDINLQPRQASRVLPNAYVVSGDSAACGLVSATSYWNQKHPMALRTSCRPPRQDHGGTFTTPFFGHVLYTGGPLEGWAKDHGGHLRHTSCQPHLVTSATPPKHCRYSGFFSHLSGRTSVRFLDRRVKILESGSTMVATTRLCTLRWPLDPLWVKVCRVHLLCALKRIRWATSVARGKPGIIAVHLAVRTVRSQHWYNAGRLNCLGAFRMLNAQLRIVAALYMANFWEYKSTDTTVTKDHNVRSRNSTGRLSDHRRRGVHAVKVHRSYLNVSLGTAYRLCNPILNFGRCYLMRTLPGESKTGSRSLPESRILSEYRGVTKPTTACFLHYASVGDVDRITLINVERHLSSIPALATEGSRIDRSSCHPDGRWIGTPRNCAITLVPRARARPRRFSQTGRRGFAGRMLIAKMSKPRTRTRKLDIPSPRDGTWSTDKATDAIFVFGNQILARSQRLQRKVLLVLTIWCRVKQDRVRGKIVSVVTNQYPRGGEQNRALFSLGQGQSCRYVPPCPIFGRCSEHENRKIIYCYHVSSSGDGLNARRSATFFIDMHTPPARLYDLFHDASCTERMNDSHRSGAQLSPVIVEMFLQKAINTPSLNWQNWSERPKRPLQQHSNRLYSSGLGTFLNALRHRKGNACYVRSPRLGYCRRRGSASYRRYVLGPRGPEERIILTTKVFIACSTKDDAFYSPQFNTRSPSGYIITARLFLDSVRCHSYHFVGDGRGNLYLTHRPCPRDLHFCRQLVNSSRYRYIRILQNRHQPLRASRPPISLLPSKYRRKPPTTSTTSGRVVRCELLPYPTHVNWIIHIHCRPPYDSPRRLSYCNTYPLSGGYALAVPRSKHIAVWLPKSLLRWANAQEEPRSINRLEGGYRVIPFTMASKCRHLRNCAPGHWIENGTVAQCLRQCRCFSSGPLRSINAQIGSGPLIARRGFRPYGLA"

	@test sample_dataset |> rna_to_aa == sample_output
	@test test_dataset   |> rna_to_aa == test_output
end; nothing
