using Test

function reverse_complement(sequence::String)
	sequence |> reverse |>
	x -> replace(x, 
			"A" => "T",
			"T" => "A",
			"C" => "G",
			"G" => "C",
		)
end

@testset "Sample & Test Datasets" begin
	sample_dataset = "AAAACCCGGT"
	file = open("datasets/rosalind_revc.txt", "r")
	test_dataset = read(file, String) |> strip |> string
	close(file)

	@test sample_dataset |> reverse_complement == "ACCGGGTTTT"
	@test test_dataset   |> reverse_complement == "ATTACACTGATTTTACGGATGATGAGTGCCCCTTGAGAGAAATTTAGTTACATACTGGGCTACCCACCCTCATAATGGTCCAGTGGTGACACTGCGAACGGAGTTGAGGGGGAAGGGCACCAAAAAATAAGTCTTCAGAGCCTTCACTTTGCATAAGCTGGGGTTTGAATTCCTATGAGAAGCCGCGCTCATAGAGTTGGGGATCATTCAATAGTCAGTGTAACCATTCAATAGATGAAGTCGGTTATAGGGTCAATTCGTTCCAGTACTACTCGTAACGTTAGCCAGAACTGAAATCCTGGAATGGTATATATACGCCAGCTCGCGGCGATAAGATTACAGGGGGTGTCGACCAAGATCTTCGAATTTGTCGAAATACACTCGGGGCATATGACCCGGTAGAACGTAATTTTGCACCCGTCTACCGTGGTCCTTCGGTGTACTAAATTGCGTACCGGCTTAAATATCTGACAGCGGACGGCCCAAATCATTAAGGGCTGGGGCACTCGCCAAATGGTAGCTGAGAGCTCGCAGTCGACAGAGCGCTTGTACCAAAATTGCCAAAGACCGCGGTTTAGCCATTCAAAGTGGTAATTCTAGGCTTATACCCCGAAAGCACGCTGACCCGCTCAGTCCTTATGATACCTCTACGGGCTGAGTTGCTCACTCTAACAAGAACGAGCATGATTAAACTTACGCGACCCGTTCAAGAGCTCAAGAGTCATTGTCAAACGGCTCATGATCAAACGTTAAGGCGCAGATGGTATCCTAGCTCTGGAGAGGTACGACAGAATGTCAAGCAGCGAGGTACCGACCACAGGCTCAGCCGTCCCCGGCAGGTTGTACAGACGATCTGAAGTGCGGCCGGCGTTGGGGGCCTCAATCCAGACGCTTACTAGGAGTTATCTGCTGGGATAATTTTAGACACTCCTCCGCCAGTCGCA"
end; nothing
